// config.js
module.exports = {
  API_KEY: process.env.TWITTER_API_KEY,
  API_SECRET: process.env.TWITTER_API_SECRET,
  ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
  ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
};
