// config.js
module.exports = {
  APT_KEY: process.env.TWITTER_APT_KEY,
  APT_SECRET: process.env.TWITTER_APT_SECRET,
  ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
  ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
};
