name: Post Tweet

on:
  workflow_dispatch:  # 手動トリガー

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Post a tweet
        run: |
          echo "Sending tweet..."
          curl -X POST "https://api.twitter.com/2/tweets" \
            -H "Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"text":"Hello world from GitHub Actions 🚀"}'
